Class {
	#name : 'Archer',
	#superclass : 'Unit',
	#category : 'SP-16-10-4-Civilization',
	#package : 'SP-16-10-4-Civilization'
}

{ #category : 'as yet unclassified' }
Archer >> attack: anEnnemi [

	anEnnemi defendAgainstArcher: self
]

{ #category : 'fighting' }
Archer >> defendAgainstKnight: aKnight [
]

{ #category : 'as yet unclassified' }
Archer >> defendAgainstPike: aPike [
]

{ #category : 'as yet unclassified' }
Archer >> defendAgainstWarrior: aWarrior [

	
]
