Class {
	#name : 'Pike',
	#superclass : 'Unit',
	#category : 'SP-16-10-4-Civilization',
	#package : 'SP-16-10-4-Civilization'
}

{ #category : 'fighting' }
Pike >> attack: anEnnemi [

	anEnnemi defendAgainstPike: self
]

{ #category : 'fighting' }
Pike >> counterAgainstArcher: anArcher [

	
]

{ #category : 'fighting' }
Pike >> counterAgainstKnight: aKnight [

	
]

{ #category : 'fighting' }
Pike >> counterAgainstPike: aPike [

	
]

{ #category : 'fighting' }
Pike >> counterAgainstWarrior: aWarrior [
	
]

{ #category : 'fighting' }
Pike >> defendAgainstArcher: anArcher [

	
]

{ #category : 'fighting' }
Pike >> defendAgainstKnight: aKnight [
]

{ #category : 'fighting' }
Pike >> defendAgainstPike: aPike [

	
]

{ #category : 'fighting' }
Pike >> defendAgainstWarrior: aWarrior [

	
]
