Class {
	#name : 'Pike',
	#superclass : 'Unit',
	#category : 'SP-16-10-4-Civilization',
	#package : 'SP-16-10-4-Civilization'
}

{ #category : 'as yet unclassified' }
Pike >> attack: anEnnemi [

	anEnnemi defendAgainstPike: self
]

{ #category : 'as yet unclassified' }
Pike >> defendAgainstArcher: anArcher [

	
]

{ #category : 'fighting' }
Pike >> defendAgainstKnight: aKnight [
]

{ #category : 'as yet unclassified' }
Pike >> defendAgainstWarrior: aWarrior [

	
]
